### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by spadidamsg** [spadidamsg/Lidar_camera_calibration#1]
Tried few onine solutions but not worked. Trying more
<img width="824" alt="Screen Shot 2020-12-21 at 4 48 23 PM" src="https://user-images.githubusercontent.com/69577392/102835969-f2b02c80-43ac-11eb-8e81-38b122135848.png">

**Comment by njadhavsg18** [comment]
Verify the following:
1. LIdar_camera_calibration is your catkin workspace 
2. To use cakin_make, you need to be in the root directory of your catkin workspace.

**Comment by spadidamsg** [comment]
Create a new catkin_ws and put the code files in the src folder of the catkin_ws and then run the catkin_make
